name: Setup Python and uv
description: Sets up Python, caches dependencies, and installs dependencies using uv.
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: Install uv
      run: pip install uv
      shell: bash

    - name: Cache uv Dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-uv-

    - name: Install Dependencies with uv
      run: |
        uv venv
        if [ "${{ inputs.dependency-file }}" = "requirements.txt" ]; then
          uv pip install -r requirements.txt
        else
          uv pip install .
        fi
      shell: bash

inputs:
  python-version:
    description: Python version to use
    required: true
  dependency-file:
    description: Dependency file to use (pyproject.toml or requirements.txt)
    required: false
    default: pyproject.toml
